<a href="https://colab.research.google.com/github/rahul-t-p/Learn-RL/blob/master/Frozen_Lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [0]:
env = gym.make("FrozenLake-v0")

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [0]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward

        if done == True: 
            break
    
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)


In [8]:
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.04400000000000003
2000 :  0.17900000000000013
3000 :  0.4120000000000003
4000 :  0.5720000000000004
5000 :  0.6520000000000005
6000 :  0.6460000000000005
7000 :  0.6970000000000005
8000 :  0.6560000000000005
9000 :  0.6900000000000005
10000 :  0.7130000000000005


In [9]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.56304584 0.52906329 0.54725516 0.5316304 ]
 [0.35982589 0.33850632 0.40696475 0.52626805]
 [0.41921398 0.42092551 0.42613077 0.48246103]
 [0.28385446 0.30951646 0.37068238 0.46249325]
 [0.5818928  0.37355922 0.36154755 0.34778987]
 [0.         0.         0.         0.        ]
 [0.21151366 0.13826414 0.28978199 0.13584042]
 [0.         0.         0.         0.        ]
 [0.37751638 0.39934078 0.52456813 0.6212228 ]
 [0.36935179 0.66835356 0.46158649 0.56474383]
 [0.57201898 0.49532876 0.44076572 0.28651991]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.41435631 0.50688396 0.73321661 0.45010849]
 [0.72177805 0.87108819 0.75605886 0.76335904]
 [0.         0.         0.         0.        ]]


In [11]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        # Choose action with highest Q-value for current state       
        # Take new action
        clear_output(wait=True)
        env.render()
        time.sleep(0.5)

        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break          
            
        # Set new state
        state = new_state
        
env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG
****You fell through a hole!****
